apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: test-cluster
  region: ap-southeast-1
nodeGroups:
   - name: nodegroup
     desiredCapacity: 1
     instanceType: t3.medium
     ssh:
        publicKeyName: test_key
