apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      run: wordpress
  replicas: 1
  template:
    metadata:
      labels:
        run: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:4.8-apache
        ports:
        - containerPort: 80